### PR TITLE
Added NuGet Announcements Repository

### PR DESCRIPTION
**Pull request by gep13**
@daveaglick haven't really dug into the code on this one, was just going by what else was in this file.  Let me know if there is anything else that I need to do here.

### CODE REVIEW

**Comment by gep13** [comment]
@daveaglick nudge 😄

**Comment by daveaglick** [comment]
Haven't forgotten about this - just haven't had a chance to bring it in yet. Since changes to the bot require publishing to Azure, I try to leave enough time after making them to ensure nothing blows up.

**Comment by gep13** [comment]
@daveaglick makes sense to me 😄

**Comment by daveaglick** [comment]
Thanks! Finally cleaning up some of the repos the bot tracks.

**Comment by gep13** [comment]
Woot! Thanks 😄

**Pull request merged**
