### PR TITLE
Code Refactoring

### PR DESCRIPTION
**Pull request by shaneray**
- Updated Microsoft.Web.WebJobs.Publish nuget package to latest version to allow build.
- Moved GitHub and Twitter specific code into their own class.
- Added configuration class.
- Added gitHubAccounts.json file for easier updating.

### CODE REVIEW

**Comment by shaneray** [comment]
@daveaglick not sure if you are interested, but I had some free time and made some changes to the project.  The main reason for this change is the `gitHubAccounts.json` that will make it much easier to see what repositories are tracked and easier to add new repositories.  This could also even be extended to just get all repositories from a specified owner rather than having to be specific for each repository.  I chose to leave it opt in on the repository for now.  I already made a lot of changes in this PR.  Another possibility with using the json rather than web.config is allowing ExcludedUsers in the web.config to be a global and allow additional users on a per repository basis.  If you are not interested, no worries... was just having some fun.  Thanks!

**Comment by daveaglick** [comment]
:shipit:

Cool, thanks! I was planning on publishing an update tonight, but I'm actually running into some time pressure getting out of my office before the weekend. I'll take a look at these changes and pull them in on Monday (I try not to do too much OSS on the weekends - that's family time for me).

**Comment by shaneray** [comment]
Thanks for the shout out on twitter.  Also one thing I just remembered... Since I added the catch{} without the throw the exception will always be swallowed.  Not sure if that is something you are concerned about with it running as a web job.  If you need it, I can issue another quick PR with the throw;

**Comment by daveaglick** [comment]
Nah, it's fine - I can grab the console output from the job with the exception details if it looks like the Tweets stop coming in. I have it rigged up with IFTTT to email me for every Tweet, so I'll notice if it starts having trouble.

Thanks again!

**Pull request merged**
